name: py38_dsnd
channels:  
  - conda-forge
  - districtdatalabs
  - anaconda 
dependencies:
 - python=3.8
 - jupyterlab 
 - pandas=1.3.2
 - scikit-learn=0.24.2
 - matplotlib=3.4.3
 - seaborn=0.11.2
 - boto3=1.18.45
 - scikit-image=0.18.3
 - pytest
 - openpyxl
 - pyarrow=5.0.0
 - py-xgboost=1.4.2
 - imbalanced-learn=0.8.0
 - yellowbrick=1.3.post1
 - scikit-learn-intelex=2021.3.0
